package us.wangxy.voicebook

import us.wangxy.voicebook.reader.xml.XmlReader
import kotlin.test.Test
import kotlin.test.assertEquals
import kotlin.test.assertNull

class XmlReaderTest {

    @Test
    fun parsesAtomFeedWithNamespaces() {
        val xml = """
            <?xml version='1.0' encoding='utf-8'?>
            <feed xmlns="http://www.w3.org/2005/Atom">
              <!-- generated by calibre-web -->
              <id>urn:uuid:123</id>
              <title>New Books</title>
              <entry>
                <title>三体</title>
                <author><name>刘慈欣</name></author>
              </entry>
            </feed>
        """.trimIndent()
        val reader = XmlReader(xml)
        val names = ArrayList<String>()
        val texts = ArrayList<Pair<String, String>>()
        while (reader.next()) {
            when (reader.eventType) {
                XmlReader.EventType.START -> names += reader.name
                XmlReader.EventType.TEXT -> texts += (reader.name to reader.text)
                XmlReader.EventType.END -> Unit
            }
        }
        assertEquals(listOf("feed", "id", "title", "entry", "title", "author", "name"), names)
        assertEquals("三体", texts.first { it.first == "title" && it.second == "三体" }.second)
        assertEquals("刘慈欣", texts.first { it.first == "name" }.second)
    }

    @Test
    fun selfClosingTagsEmitSyntheticEnd() {
        val reader = XmlReader("<root><link rel=\"a\" href=\"b\"/><img src=\"x\"/></root>")
        reader.next() // root start
        reader.next() // link start
        assertEquals("link", reader.name)
        assertEquals("a", reader.attribute("rel"))
        assertEquals("b", reader.attribute("href"))
        reader.next() // link end (synthetic)
        assertEquals(XmlReader.EventType.END, reader.eventType)
        assertEquals("link", reader.name)
        reader.next() // img start
        assertEquals("img", reader.name)
        reader.next() // img end
        reader.next() // root end
        assertEquals("root", reader.name)
        assertNull(reader.next().let { if (it) "" else null })
    }

    @Test
    fun decodesEntitiesAndCdata() {
        val reader = XmlReader("<t>a &amp; b &#20013; &#x6587; <![CDATA[x < y & z]]></t>")
        val collected = StringBuilder()
        while (reader.next()) {
            if (reader.eventType == XmlReader.EventType.TEXT) collected.append(reader.text)
        }
        assertEquals("a & b 中 文x < y & z", collected.toString())
    }

    @Test
    fun unknownEntityPassesThrough() {
        val reader = XmlReader("<t>&nbsp;&weird;</t>")
        reader.next() // t START
        reader.next() // text
        assertEquals("&nbsp;&weird;", reader.text)
    }

    @Test
    fun multilineAttributes() {
        val reader = XmlReader(
            """
            <root>
              <item
                id="7"
                data-x = 'y z'
              >body</item>
            </root>
            """.trimIndent(),
        )
        reader.next() // root
        reader.next() // item
        assertEquals("item", reader.name)
        assertEquals("7", reader.attribute("id"))
        assertEquals("y z", reader.attribute("data-x"))
        reader.next() // text
        assertEquals("body", reader.text)
    }
}
